 
spring:
  datasource:
    url: jdbc:postgresql://localhost:9432/bank_db?user=postgres&password=postgres
  jpa:
    properties:
      hibernate:
        # Fix Postgres JPA Error:
        # Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
        temp:
          use_jdbc_metadata_defaults: false
          
logging:
  level:    
    root: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.orm.jpa: DEBUG      
    org.springframework.transaction: DEBUG
    org.hibernate.engine: DEBUG
    org.hibernate.SQL: DEBUG    
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE